### ISSUE TITLE
Migrate to @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers

### ISSUE THREAD

**Issue by coderasm** [symfoni/hardhat-plugins#10]
See the beginning installation instructions for hardhat-deploy-ethers.
https://hardhat.org/plugins/hardhat-deploy-ethers.html#installation
From hardhat-deploy-ethers installation:
>Since hardhat-deploy-ethers is a fork of @nomiclabs/hardhat-ethers and that other plugin might have an hardcoded dependency on @nomiclabs/hardhat-ethers the best way to install hardhat-deploy-ethers and ensure compatibility is the following:
`npm install --save-dev @nomiclabs/hardhat-ethers@npm:hardhat-deploy-ethers ethers`

Only `import "@nomiclabs/hardhat-ethers";` is needed now.

**Comment by RobertoSnap** [comment]
@coderasm Yes, i will fix this in next update! Thank you!
