### ISSUE TITLE
Include Walletconnect out of the box

### ISSUE THREAD

**Issue by ramvi** [symfoni/hardhat-plugins#2]
Missing configuration setup and configuration parsing

**Comment by RobertoSnap** [comment]
Wallet Connect configuration added, follow this configuration to add it to hardhat-react. 

https://github.com/symfoni/hardhat-plugins/tree/master/packages/hardhat-react#walletconnect

Fixed with commit: https://github.com/symfoni/hardhat-plugins/commit/d3b99432fd8f7054ea4d61163308dd7cff0bbb83

**Comment by RobertoSnap** [comment]
Working in demo app 
![image](https://user-images.githubusercontent.com/4772930/104726269-a221ba00-5733-11eb-8c9e-e82af972b399.png)

**Comment by RobertoSnap** [comment]
Added support for custom RPC 0.1.10
