### ISSUE TITLE
Support multiple instances deployed as proxies of the same contract

### ISSUE THREAD

**Issue by ramvi** [symfoni/hardhat-plugins#3]
Support multiple instances deployed as proxies of the same contract. Hardhat-react have trouble parsing such deployments. 

Say I have a Token.sol and I deploy 3 instances of it, which are TokenA, TokenB, and TokenC. Last time I checked, the hardhat-deploy will generate a Token.json and have TokenA, TokenB, TokenC, and their addresses inside the same JSON file. While hardhat-react only looked for the JSON files to create corresponding contract instances, it will only have Token component generated without any instance.

My workaround is to explicitly create contracts TokenA, TokenB, and TokenC inheriting from Token, and then deploy each of them to have TokenA.json, TokenB.json, TokenC.json generated respectively.

**Comment by RobertoSnap** [comment]
Added support and name resolving of probable contract instances like in the example above. The demo project now includes an example of this. Please try version 0.1.9

Here is readme of how it works: 

https://github.com/symfoni/hardhat-plugins/tree/master/packages/hardhat-react#contract-instances

Should create a context for each instance and same types:
![image](https://user-images.githubusercontent.com/4772930/104811671-73701600-57fd-11eb-9ecb-b780297ac044.png)
