### ISSUE TITLE
Contract address is 0x00.. after successful deployment in hardhat local network

### ISSUE THREAD

**Issue by Bidon15** [symfoni/hardhat-plugins#5]
Hey folks!

I was trying out some basic stuff with the hardhat-react plugin and got stuck with connecting to the deployed contract in hardhat local network

https://github.com/Bidon15/piggybank/blob/master/frontend/src/components/PiggyBank.tsx
https://github.com/Bidon15/piggybank/blob/master/hardhat.config.ts
https://github.com/Bidon15/piggybank/blob/master/scripts/deploy.ts

Is it really an issue or what am I getting wrong?

**Comment by RobertoSnap** [comment]
Hi, sorry for late reply

If an instance was NOT deployed by hardhat-deploy, it will be set to a zero address. This way makes it easier to connect with another contract address in you frontend with for example erc20.instance?.attach("SOME_ADDRESS")

**Comment by RobertoSnap** [comment]
If you have a deploy scipt that successfully deploys the contract, it will inject that address into the context. Can you check if you get the hardhat-deploy file for Piggybank when running harhat to generate the React context

**Comment by Bidon15** [comment]
Thanks for the explanation @RobertoSnap ! 
Indeed, I had no deploy script, so the contract address is 0x00 
Now it's all good!
