### ISSUE TITLE
typechain's index.ts file removed by hardhat-react

### ISSUE THREAD

**Issue by heri16** [symfoni/hardhat-plugins#7]
https://github.com/symfoni/symfoni-monorepo/blob/fc0722089528ca02d0330ebdb66beba4e8e9f76c/packages/hardhat-react/src/TsMorhProject.ts#L148

Not sure why the `index.ts` file that has been generated by typechain should be removed by this library. 

Other plugins might depend on it.

**Comment by RobertoSnap** [comment]
Hi @heri16 Great catch! We did it as a quik fix because it would break typecheck in some scenarioes. With new version of typechain we dont need to do this anymore, expect a new release with these changes implemented.
