### ISSUE TITLE
setSigner() should update the contacts signer.

### ISSUE THREAD

**Issue by heri16** [symfoni/hardhat-plugins#8]
Calling setSigner from SignerContext currently does nothing.

It should automatically update the ethers contracts.

**Comment by RobertoSnap** [comment]
Yes, i have been working on a better way to accomplish this. Where we pre fetch what possible signers are available from you hardhat configuration, then you can issue an intension to switch to one of these signers and it will try to make the switch. 

Is there a scenario where you need to set the signer from something you would not know at compile time?

**Comment by RobertoSnap** [comment]
New Symfoni Context inferface we are tying looks like this,

```ts
export interface SymfoniContextInterface {
    init: (opts?: InitOpts) => void
    messages: string[];
    forceSigner: boolean
    chainId?: number
    providers: typeof PROVIDERS;
    selectedProvider: ProviderTypes
    provider: providers.Provider
    signers: typeof SIGNERS
    selectedSigner: SignerTypes
// setSelectedSigner: (signerName) => Promise<boolean>
    signer?: Signer
    address?: string
    loading: boolean
    ready: boolean
    hasSigner: boolean
}```

I will migrate it from a client project into symfoni-monorepo asap.
